# set vi movement keys
bindkey -v

# set editor to nvim
export EDITOR=nvim
export VISUAL=nvim

# set architecture flags
export ARCHFLAGS="-arch x86_64"

# set command prompt
source "/usr/local/opt/zsh-git-prompt/zshrc.sh"
setopt prompt_subst
export PS1='%n@%m %. $(git_super_status)
%# '

# assume bare words are an attempt to cd to that dir
setopt auto_cd

# set history params
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.history

# allow ESC-q to stash the current line
bindkey '\eq' push-line-or-edit

# set up completions in general
autoload -U compinit
compinit

# set up some useful aliases
alias ll='ls -lh'
alias be='bundle exec'
alias resource='. ~/.zshrc'
alias gs='git status'
alias config='cd ~/.conf'
alias facenv='devkit env start; eval "$(devkit env vars)"'
alias facstart='facenv; bundle exec rails server'
function work() { jump $1 dev }
function hack() { jump $1 dev/hacks }
function doc() { jump $1 dev/docs }
function hiring() { jump $1 dev/hiring }
function jump() {
  if [ -z $1 ]; then
    cd ~/${2}
  else
    cd `ls -dt1 ~/${2}/${1}* | head -n1`
  fi
}
alias wk='work'

# configure chruby to be available and auto-detecting
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh

# ensure brew python is used if installed
PATH="/usr/local/opt/python/libexec/bin:$PATH"
PATH="/usr/local/sbin:$PATH"

# allow default scripts to live in ./bin
PATH="./bin:$PATH"
