---
- hosts: all
  roles:
    - homebrew
    - git
    - vim
    - ruby
    - libxml2
    - bash
    - zsh
    - tmux
    - dev
    - ag
- hosts: freeagent
  roles:
    - freeagent
    - postgresql
- hosts: home
  roles:
    - cordova
    - encryptme
    - postgresql
    - backblaze
    - yarn
    - imagemagick
    - heroku
    - transporter
    - vmware
    - duet
    - basecamp
    - sketch
    - microsoft-office
- hosts: fun
  roles:
    - steam
