---
- name: install git
  homebrew: name=git
- name: configure git name
  git_config:
    name: user.name
    scope: global
    value: "{{ full_name }}"
- name: configure git email address
  git_config:
    name: user.email
    scope: global
- name: configure git color
  git_config:
    name: color.ui
    scope: global
    value: true
- name: configure git editor
  git_config:
    name: core.editor
    scope: global
    value: /usr/bin/env vim
