---
- name: install git and helpers
  homebrew:
    name: ['git', 'zsh-git-prompt']
- name: configure git name
  git_config:
    name: user.name
    scope: global
    value: "{{ full_name }}"
- name: configure git email address
  git_config:
    name: user.email
    scope: global
    value: "{{ email_address }}"
- name: configure git color
  git_config:
    name: color.ui
    scope: global
    value: true
