" set encoding
set encoding=utf-8
" disable filetype detection before running Vundle
filetype off

" ______ PLUGINS ______
" include Vundle bundle in realtime path
set rtp+=~/.vim/bundle/Vundle.vim
" begin Vundle operations
call vundle#begin()
" allow Vundle to manage Vundle
Plugin 'VundleVim/Vundle.vim'

" install base16 colors
Plugin 'chriskempson/base16-vim'

" install Ack for smarter file searching
Plugin 'mileszs/ack.vim'
" install trailing whitespace to highlight trailing whitespace
Plugin 'bronson/vim-trailing-whitespace'
" install ctrlp for fuzzy file finding
Plugin 'ctrlpvim/ctrlp.vim'
" install nerdtree
Plugin 'scrooloose/nerdtree'
" install surround for paren
Plugin 'tpope/vim-surround'
" install ragtag for HTML tag completion
Plugin 'tpope/vim-ragtag'
" install commentary for quick commenting
Plugin 'tpope/vim-commentary'

" install SCSS syntax
Plugin 'cakebaker/scss-syntax.vim'
" install Ansible syntax
Plugin 'pearofducks/ansible-vim'
" install Puppet syntax
Plugin 'rodjek/vim-puppet'
" install emmet support
Plugin 'mattn/emmet-vim'

" install Rails support
Plugin 'tpope/vim-rails'

" finish Vundle operations
call vundle#end()
" ---------------------

" enable filetype detection after running Vundle to allow new types to be picked up
filetype plugin indent on

" unless syntax highlighting is already enabled…
if !exists('g:syntax_on')
  " enable syntax highlighting
  syntax enable
endif
" if ag is available on the system…
if executable('ag')
  " configure Ack to use ag
  let g:ackprg = 'ag --vimgrep'
endif
" configure ctrlp
let g:ctrlp_show_hidden = 1 " show hidden files
" exclude certain directories, files etc
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](node_modules|\.git|tmp|log)$',
  \ }

" enables 24-bit color
set termguicolors
" Access colors present in 256 colorspace
let base16colorspace=256
" chooses colorscheme
colorscheme base16-ocean

" follows indent of previous line when creating a new line
set autoindent
" follows language-specific indenting rules when creating a new line
set smartindent
" configures folding
set foldmethod=syntax foldlevelstart=30
" configures tabs
set tabstop=2 shiftwidth=2 expandtab
" highlight line containing cursor
set cursorline
" split below and right
set splitbelow splitright
" make searching case insensitive unless the query has capital letters.
set ignorecase smartcase
" Use 'g' flag by default with :s/foo/bar/.
set gdefault
" Use 'magic' patterns (extended regular expressions).
set magic
" highlight 100th column
set colorcolumn=100

" defines tab and trailing space indicators
set listchars=tab:>-,trail:-
" displays hidden characters such as spaces and tabs
set list

" show line numbers
set number
" highlight the results of the last search
set hlsearch
" run substitutions incrementally
" set inccommand=nosplit
" disable saving of swapfiles
set noswapfile
" allow find to recursively search directories
set path+=**

" enable nerdtree toggling
map <C-n> :NERDTreeToggle<CR>
