---
- name: install vim
  homebrew: name=vim options=with-python3
- name: configure vim
  copy: src=vimrc dest=~/.vimrc
- name: create vim bundle directory
  file: path={{ item }} state=directory
  with_items:
    - ~/.vim
    - ~/.vim/bundle
- name: install vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
- name: install plugins
  command: vim +PluginInstall +qall --noplugin
