---
- name: install dev utilities
  homebrew: name={{ item }}
  with_items:
    - tree
    - watch
- name: install dev software
  homebrew_cask: name={{ item }}
  with_items:
    - iterm2
    - ngrok
    - visual-studio-code
    - sublime-text
- name: set up dev directories
  file: name={{ item }} state=directory
  with_items:
    - ~/dev
    - ~/dev/hacks
    - ~/dev/docs
    - ~/dev/hiring
    - ~/dev/archive
