---
- name: install dev software
  homebrew_cask: name={{ item }}
  with_items:
    - iterm2
    - firefoxdeveloperedition
    - ngrok
- name: set up dev directories
  file: name={{ item }} state=directory
  with_items:
    - ~/dev
    - ~/dev/hacks
    - ~/dev/archive
