---
- name: install neovim
  homebrew: name=neovim
- name: ensure config directory exists
  file: path={{ item }} state=directory
  with_items:
    - ~/.config
    - ~/.config/nvim
- name: configure neovim
  copy: src=init.vim dest=~/.config/nvim/init.vim
- name: create vim bundle directory
  file: path={{ item }} state=directory
  with_items:
    - ~/.vim
      ~/.vim/bundle
- name: install vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
