---
- name: install neovim
  homebrew: name=neovim
- name: install python
  homebrew: name=python
- name: ensure neovim has python access
  command: pip2 install --upgrade neovim
- name: install python3
  homebrew: name=python3
- name: ensure neovim has python access
  command: pip3 install --upgrade neovim
- name: ensure config directory exists
  file: path={{ item }} state=directory
  with_items:
    - ~/.config
    - ~/.config/nvim
- name: configure neovim
  copy: src=../vim/files/vimrc dest=~/.config/nvim/init.vim
- name: create vim bundle directory
  file: path={{ item }} state=directory
  with_items:
    - ~/.vim
      ~/.vim/bundle
- name: install vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
- name: install plugins
  command: nvim +PluginInstall +qall
