---
- name: install chruby and ruby-install
  homebrew: name={{ item }}
  with_items:
    - chruby
    - ruby-install
- name: update ruby-install
  command: ruby-install -L
- name: install rubies
  command: ruby-install --no-reinstall {{ item }}
  with_items:
    - ruby 2.1.5
    - ruby 2.1.9
    - ruby 2.2.3
    - ruby 2.3.1
    - ruby 2.3.4
    - ruby 2.3.5
    - ruby 2.4.1
    - ruby 2.4.2
- name: set default ruby
  copy: src=ruby-version dest=~/.ruby-version
