---
- name: install chruby and ruby-install
  homebrew: name={{ item }}
  with_items:
    - chruby
    - ruby-install
- name: install rubies
  command: ruby-install --no-reinstall {{ item }}
  with_items:
    - ruby 2.3.1
    - ruby 2.3.5
    - ruby 2.4.1
    - ruby 2.4.2
    - ruby 2.3.4
