---
- name: install chruby and ruby-install
  homebrew:
    name: ['chruby', 'ruby-install']
- name: update ruby-install
  command: ruby-install -L
- name: install rubies
  command: ruby-install --no-reinstall {{ item }}
  with_items:
    - ruby 2.3.7
    - ruby 2.5.3
    - ruby 2.6.2
- name: set default ruby
  copy: src=ruby-version dest=~/.ruby-version
